"""
src/test_config/domain_0.py

Pydantic v2 configuration models for Domain 0 (API Discovery and Inventory
Management) tests.

This module follows the same structure as domain_4.py, domain_6.py, etc.
It owns all per-test tuning parameters for tests 0.x, keeping them isolated
from the other domain schemas.

Tests in this domain:
    0.1 -- Shadow API Discovery                 (P0, BLACK_BOX)
    0.2 -- Gateway Deny-by-Default              (P0, BLACK_BOX)
    0.3 -- Deprecated API Enforcement           (P0, BLACK_BOX)

Every test has its model (an empty one when it has no parameters). Test 0.3
uses only values derivable from the OpenAPI spec or RFC-mandated constants
(e.g. HTTP 410 Gone, the Sunset header name), so its model is empty.

Dependency rule: imports only from pydantic and the stdlib.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Constants -- Test 0.1
# ---------------------------------------------------------------------------

# Number of documented endpoints taken (in spec order) by the undeclared-method
# sub-check; parametric endpoints among them are skipped. Each sampled endpoint
# receives up to about five undeclared methods, so 10 means about 50 requests.
# Bounds are safety rails: below 1 the sub-check would do nothing, above 100 a
# typo would send a burst of hundreds of requests. 10 is the v0.1.0 behaviour.
TEST_01_METHOD_PROBE_SAMPLE_SIZE_DEFAULT: int = 10
TEST_01_METHOD_PROBE_SAMPLE_SIZE_MIN: int = 1
TEST_01_METHOD_PROBE_SAMPLE_SIZE_MAX: int = 100

# ---------------------------------------------------------------------------
# Constants -- Test 0.2
# ---------------------------------------------------------------------------

# Default Server header identifiers that indicate the response was generated
# by an API Gateway (not a backend application server).
# Checked as case-insensitive substrings of the raw 'Server' header value.
#
# Rationale for each entry:
#   kong       -- Kong Gateway (our target gateway in the test environment)
#   nginx      -- NGINX (common reverse proxy / gateway; also Kong's base)
#   openresty  -- OpenResty (NGINX + LuaJIT; Kong OSS is built on OpenResty)
#   apache     -- Apache httpd (common reverse proxy)
#   caddy      -- Caddy v2 (API-first reverse proxy / gateway)
#   traefik    -- Traefik (cloud-native edge router / gateway)
#   envoy      -- Envoy Proxy (Istio / service mesh data plane)
TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT: list[str] = [
    "kong",
    "nginx",
    "openresty",
    "apache",
    "caddy",
    "traefik",
    "envoy",
]


# ---------------------------------------------------------------------------
# Test 0.2 -- Deny-by-Default
# ---------------------------------------------------------------------------


class Test02ProbeConfig(BaseModel):
    """
    Tuning parameters for Test 0.2 (Gateway Deny-by-Default on Unregistered Paths).

    The only configurable parameter is the list of 'Server' response header
    substrings used to identify a known API Gateway in the backend-header
    detection sub-check.

    Why this is config-driven:
        The 'Server' header check classifies a response as "backend-generated"
        when the header value does not contain any known Gateway identifier.
        Organisations that deploy less common gateways (HAProxy, Tyk, APISIX,
        3scale) or configure a custom Server header on Kong (e.g. via the
        'headers' directive) would otherwise receive systematic false positives
        on every probe. The operator can extend or replace the default list to
        match their actual stack.

    Usage in Test 0.2:
        cfg = target.tests_config.test_0_2
        gateway_identifiers: frozenset[str] = frozenset(cfg.gateway_server_identifiers)
        # Then: any(gw_id in server_header.lower() for gw_id in gateway_identifiers)

    Security implication of extending the list:
        Adding an identifier reduces the sensitivity of the Server-header
        sub-check for that value. Entries should identify the Gateway layer
        (Kong, NGINX), not the application layer (Gunicorn, uWSGI, Node).
        Never add application server names: doing so defeats the purpose of
        the sub-check.
    """

    model_config = {"frozen": True, "extra": "forbid"}

    gateway_server_identifiers: tuple[str, ...] = Field(
        default_factory=lambda: tuple(TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT),
        min_length=1,
        description=(
            "Substrings matched case-insensitively against the 'Server' response header "
            "to classify a response as generated by the API Gateway layer (not the backend). "
            "A response whose Server header does NOT contain any of these substrings is "
            "flagged as a deny-by-default violation: the request reached the backend. "
            f"Default: {TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT}. "
            "Extend when deploying gateways not in this list (HAProxy, Tyk, APISIX). "
            "Never add application server names (Gunicorn, uWSGI): that defeats the check."
        ),
    )


# ---------------------------------------------------------------------------
# Test 0.1 and 0.3 models
# ---------------------------------------------------------------------------


class Test01Config(BaseModel):
    """
    Configuration for Test 0.1 (Shadow API Discovery).

    Path in config.yaml: tests.domain_0.test_0_1
    """

    model_config = {"frozen": True, "extra": "forbid"}

    method_probe_sample_size: Annotated[
        int,
        Field(ge=TEST_01_METHOD_PROBE_SAMPLE_SIZE_MIN, le=TEST_01_METHOD_PROBE_SAMPLE_SIZE_MAX),
    ] = Field(
        default=TEST_01_METHOD_PROBE_SAMPLE_SIZE_DEFAULT,
        description=(
            "Number of documented endpoints (in spec order) used by the undeclared-method "
            "sub-check; parametric ones among them are skipped. Each receives up to about "
            "five undeclared methods. Range 1-100, default 10."
        ),
    )


class Test03Config(BaseModel):
    """
    Configuration for Test 0.3 (Deprecated API Enforcement): no parameters.

    The model exists so that every native test has one (convention). Path in
    config.yaml: tests.domain_0.test_0_3 (empty).
    """

    model_config = {"frozen": True, "extra": "forbid"}


# ---------------------------------------------------------------------------
# Domain-level aggregator
# ---------------------------------------------------------------------------


class TestDomain0Config(BaseModel):
    """
    Aggregator for all Domain 0 (API Discovery and Inventory Management) test configs.

    One field per test (every test has a model, possibly empty).

    Adding a new Domain 0 test requires:
        1. Defining a Test0XProbeConfig/AuditConfig model above.
        2. Adding a field here.
        3. Adding a field to RuntimeTestsConfig (src/test_config/runtime.py); the engine
           wires it automatically (RuntimeTestsConfig.from_domains).
        4. Adding the key to config.yaml under tests.domain_0.
    """

    model_config = {"frozen": True, "extra": "forbid"}

    test_0_1: Test01Config = Field(
        default_factory=Test01Config,
        description="Test 0.1 (Shadow API Discovery) parameters.",
    )
    test_0_3: Test03Config = Field(
        default_factory=Test03Config,
        description="Test 0.3 (Deprecated API Enforcement): no parameters.",
    )
    test_0_2: Test02ProbeConfig = Field(
        default_factory=Test02ProbeConfig,
        description=(
            "Probe parameters for Test 0.2 (Gateway Deny-by-Default on Unregistered Paths). "
            "Maps to 'tests.domain_0.test_0_2' in config.yaml."
        ),
    )
