"""
src/config/schema/domain_0.py

Pydantic v2 configuration models for Domain 0 (API Discovery and Inventory
Management) tests.

This module follows the same structure as domain_4.py, domain_6.py, etc.
It owns all per-test tuning parameters for tests 0.x, keeping them isolated
from the other domain schemas.

Tests in this domain:
    0.1 -- Shadow API Discovery                 (P0, BLACK_BOX)
    0.2 -- Gateway Deny-by-Default              (P0, BLACK_BOX)
    0.3 -- Deprecated API Enforcement           (P0, BLACK_BOX)

Currently only Test 0.2 has configurable parameters. Tests 0.1 and 0.3 use
only values derivable from the OpenAPI spec or RFC-mandated constants (e.g.
HTTP 410 Gone, the Sunset header name) and do not require operator overrides.

Dependency rule: imports only from pydantic and the stdlib.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Constants -- Test 0.2
# ---------------------------------------------------------------------------

# Default Server header identifiers that indicate the response was generated
# by an API Gateway (not a backend application server).
# Checked as case-insensitive substrings of the raw 'Server' header value.
#
# Rationale for each entry:
#   kong       -- Kong Gateway (our target gateway in the test environment)
#   nginx      -- NGINX (common reverse proxy / gateway; also Kong's base)
#   openresty  -- OpenResty (NGINX + LuaJIT; Kong OSS is built on OpenResty)
#   apache     -- Apache httpd (common reverse proxy)
#   caddy      -- Caddy v2 (API-first reverse proxy / gateway)
#   traefik    -- Traefik (cloud-native edge router / gateway)
#   envoy      -- Envoy Proxy (Istio / service mesh data plane)
TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT: list[str] = [
    "kong",
    "nginx",
    "openresty",
    "apache",
    "caddy",
    "traefik",
    "envoy",
]


# ---------------------------------------------------------------------------
# Test 0.2 -- Deny-by-Default
# ---------------------------------------------------------------------------


class Test02ProbeConfig(BaseModel):
    """
    Tuning parameters for Test 0.2 (Gateway Deny-by-Default on Unregistered Paths).

    The only configurable parameter is the list of 'Server' response header
    substrings used to identify a known API Gateway in the backend-header
    detection sub-check.

    Why this is config-driven:
        The 'Server' header check classifies a response as "backend-generated"
        when the header value does not contain any known Gateway identifier.
        Organisations that deploy less common gateways (HAProxy, Tyk, APISIX,
        3scale) or configure a custom Server header on Kong (e.g. via the
        'headers' directive) would otherwise receive systematic false positives
        on every probe. The operator can extend or replace the default list to
        match their actual stack.

    Usage in Test 0.2:
        cfg = target.tests_config.test_0_2
        gateway_identifiers: frozenset[str] = frozenset(cfg.gateway_server_identifiers)
        # Then: any(gw_id in server_header.lower() for gw_id in gateway_identifiers)

    Security implication of extending the list:
        Adding an identifier reduces the sensitivity of the Server-header
        sub-check for that value. Entries should identify the Gateway layer
        (Kong, NGINX), not the application layer (Gunicorn, uWSGI, Node).
        Never add application server names: doing so defeats the purpose of
        the sub-check.
    """

    model_config = {"frozen": True}

    gateway_server_identifiers: list[str] = Field(
        default_factory=lambda: list(TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT),
        min_length=1,
        description=(
            "Substrings matched case-insensitively against the 'Server' response header "
            "to classify a response as generated by the API Gateway layer (not the backend). "
            "A response whose Server header does NOT contain any of these substrings is "
            "flagged as a deny-by-default violation: the request reached the backend. "
            f"Default: {TEST_02_GATEWAY_SERVER_IDENTIFIERS_DEFAULT}. "
            "Extend when deploying gateways not in this list (HAProxy, Tyk, APISIX). "
            "Never add application server names (Gunicorn, uWSGI): that defeats the check."
        ),
    )


# ---------------------------------------------------------------------------
# Domain-level aggregator
# ---------------------------------------------------------------------------


class TestDomain0Config(BaseModel):
    """
    Aggregator for all Domain 0 (API Discovery and Inventory Management) test configs.

    One field per test that has configurable parameters. Currently only test_0_2
    has tuning parameters; 0.1 and 0.3 are intentionally absent (they have no
    operator-tunable values beyond what the OpenAPI spec provides).

    Adding a new Domain 0 test with parameters requires:
        1. Defining a Test0XProbeConfig/AuditConfig model above.
        2. Adding a field here.
        3. Adding the corresponding RuntimeTest0XConfig in core/models/runtime.py.
        4. Populating it in engine.py Phase 3.
        5. Adding the key to config.yaml under tests.domain_0.
    """

    model_config = {"frozen": True}

    test_0_2: Test02ProbeConfig = Field(
        default_factory=Test02ProbeConfig,
        description=(
            "Probe parameters for Test 0.2 (Gateway Deny-by-Default on Unregistered Paths). "
            "Maps to 'tests.domain_0.test_0_2' in config.yaml."
        ),
    )
