"""
src/core/redaction.py

Redaction of secret values in the evidence and the reports.

Principle (OPEN_QUESTIONS Q-31, owner decision): redact only secret values,
never what proves a finding, and keep the meaning with typed placeholders
("[REDACTED: user_a token]" instead of a bare "[REDACTED]").

SecretRegistry holds the secrets known during a run (tokens acquired for a
role, a token created by a test, a secret generated by the tool), each with
a label. It is applied twice with the same rules:
    1. when an HTTP transaction is captured (SecurityClient), so that no
       known secret reaches the evidence files written during the run;
    2. when the final outputs are written (Phase 7: evidence.json, the JSON
       and HTML reports), for secrets learned after their capture (e.g. the
       token in the response that creates it).

Headers that carry credentials by definition are redacted even when their
value is not registered: Authorization (labelled by the registered secret it
contains, else by its scheme) and Cookie / Set-Cookie (value redacted, cookie
name and attributes kept: they are what test 1.6 judges).

Response bodies are not redacted beyond the registered secrets: they are
often the proof itself (e.g. test 6.4).

Dependency rule: imports only from the standard library.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Shortest value accepted as a secret. Registered secrets are replaced
# wherever they appear, so a short value could hit ordinary text; the tool's
# secrets are 32-40 characters (tokens, generated secrets).
MIN_SECRET_LENGTH: int = 8

# Placeholder layout: "[REDACTED: <label>]"; bare "[REDACTED]" when no label.
# Both start with REDACTED_MARKER_PREFIX, which tells a redacted value apart.
REDACTED_MARKER_PREFIX: str = "[REDACTED"
REDACTED_PLACEHOLDER: str = REDACTED_MARKER_PREFIX + "]"
_LABELLED_PLACEHOLDER_TEMPLATE: str = REDACTED_MARKER_PREFIX + ": {label}]"

# Characters a label must not contain: placeholders are written inside JSON
# strings and must not need escaping.
_FORBIDDEN_LABEL_CHARACTERS: frozenset[str] = frozenset('"\\\n\r')

# Prefix of a public probe value stored in clear: a value a test declares as
# not secret (e.g. a deliberately malformed Authorization value of test 1.1).
# It keeps the EvidenceRecord safety net able to tell it from a raw credential;
# the HTML report strips it to rebuild the exact request (copy as cURL).
PUBLIC_VALUE_PREFIX: str = "[public probe] "

# Header names (lowercase) whose value is a credential by definition.
AUTHORIZATION_HEADER: str = "authorization"
COOKIE_HEADER: str = "cookie"
SET_COOKIE_HEADER: str = "set-cookie"

# Label of an Authorization value that contains no registered secret, by
# scheme ("Basic credentials", "Bearer credentials"); "credentials" alone
# when the value has no scheme.
_UNKNOWN_CREDENTIALS_LABEL: str = "credentials"

# Separators of the Cookie / Set-Cookie syntax (RFC 6265).
_COOKIE_PAIR_SEPARATOR: str = ";"
_COOKIE_NAME_VALUE_SEPARATOR: str = "="

# Scheme of an Authorization value: the first token before a space.
_AUTH_SCHEME_PATTERN: re.Pattern[str] = re.compile(r"^(?P<scheme>[A-Za-z][A-Za-z0-9._~+/-]*)\s+\S")


def placeholder(label: str) -> str:
    """
    Return the typed placeholder for a label.

    Args:
        label: What the hidden value was, e.g. "user_a token".

    Returns:
        "[REDACTED: <label>]".
    """
    return _LABELLED_PLACEHOLDER_TEMPLATE.format(label=label)


class SecretRegistry:
    """
    The secrets known during one run, each with a label, and their redaction.

    Held by TestContext (tests and helpers register secrets through it) and
    used by SecurityClient at capture and by the engine in Phase 7.
    """

    def __init__(self) -> None:
        """Start with no registered secret and no declared public value."""
        self._labels: dict[str, str] = {}
        self._public_values: set[str] = set()

    def declare_public(self, value: str) -> None:
        """
        Declare a value a test sends on purpose and that is not a secret.

        An Authorization header equal to it is stored in clear, prefixed with
        PUBLIC_VALUE_PREFIX, instead of being redacted (a registered secret
        inside the value still wins). Meant for fixed probe values written in
        the code of a test, never for anything received or configured.

        Args:
            value: The exact header value the test sends.
        """
        self._public_values.add(value)

    def register(self, value: str, label: str) -> None:
        """
        Register a secret value with the label that will replace it.

        Values shorter than MIN_SECRET_LENGTH are ignored (see the constant).
        Registering the same value again replaces its label.

        Args:
            value: The secret, exactly as it appears in requests and responses.
            label: What it is, e.g. "user_a token" (no quotes or backslashes).

        Raises:
            ValueError: If the label is empty or contains a forbidden character.
        """
        if not label.strip() or any(char in _FORBIDDEN_LABEL_CHARACTERS for char in label):
            raise ValueError(
                "Secret label must be non-empty, without quotes, backslashes or "
                f"newlines: {label!r}"
            )
        if len(value) < MIN_SECRET_LENGTH:
            return
        self._labels[value] = label

    def redact(self, text: str) -> str:
        """
        Replace every registered secret in text with its placeholder.

        Longer secrets are replaced first, so that a secret containing another
        one is labelled as a whole.

        Args:
            text: Any text: a body, a URL, a serialized JSON document.

        Returns:
            The text with no registered secret left.
        """
        for value in sorted(self._labels, key=len, reverse=True):
            if value in text:
                text = text.replace(value, placeholder(self._labels[value]))
        return text

    def redact_header(self, name: str, value: str) -> str:
        """
        Redact one header value (name compared case-insensitively).

        Authorization: the placeholder of the registered secret it contains;
        else, a declared public value prefixed with PUBLIC_VALUE_PREFIX; else
        the placeholder of its scheme ("[REDACTED: Basic credentials]"). Cookie and
        Set-Cookie: each value redacted, names and attributes kept. Any other
        header: registered secrets replaced.

        Args:
            name:  Header name.
            value: Header value as sent or received.

        Returns:
            The value to store.
        """
        lower_name = name.lower()
        if lower_name == AUTHORIZATION_HEADER:
            return self._redact_authorization(value)
        if lower_name == COOKIE_HEADER:
            return _COOKIE_PAIR_SEPARATOR.join(
                _redact_cookie_pair(pair) for pair in value.split(_COOKIE_PAIR_SEPARATOR)
            )
        if lower_name == SET_COOKIE_HEADER:
            first_pair, separator, attributes = value.partition(_COOKIE_PAIR_SEPARATOR)
            return _redact_cookie_pair(first_pair) + separator + attributes
        return self.redact(value)

    def _redact_authorization(self, value: str) -> str:
        """Return the placeholder for an Authorization value, or a declared public value."""
        for secret in sorted(self._labels, key=len, reverse=True):
            if secret in value:
                return placeholder(self._labels[secret])
        if value in self._public_values:
            return PUBLIC_VALUE_PREFIX + value
        scheme_match = _AUTH_SCHEME_PATTERN.match(value)
        if scheme_match is None:
            return placeholder(_UNKNOWN_CREDENTIALS_LABEL)
        return placeholder(f"{scheme_match.group('scheme')} {_UNKNOWN_CREDENTIALS_LABEL}")


def _redact_cookie_pair(pair: str) -> str:
    """Return "name=[REDACTED]" for a "name=value" cookie pair (spacing kept)."""
    name, separator, _value = pair.partition(_COOKIE_NAME_VALUE_SEPARATOR)
    if not separator:
        return pair
    return f"{name}{separator}{REDACTED_PLACEHOLDER}"
